In [ ]:
import sqlite3
import pandas as pd

df_orders = pd.read_csv('olist_orders_dataset.csv')
df_items = pd.read_csv('olist_order_items_dataset.csv')
df_products = pd.read_csv('olist_products_dataset.csv')

conn = sqlite3.connect('ecommerce.db')


df_orders.to_sql('orders', conn, index=False, if_exists='replace')
df_items.to_sql('order_items', conn, index=False, if_exists='replace')
df_products.to_sql('products', conn, index=False, if_exists='replace')

print("Done")

sql = """ SELECT * from df_orders"""

Database ecommerce.db berhasil dibuat dan siap dipake!

In [ ]:
# Query 1: Counting total orders and revenue
query_summary = """
SELECT 
    COUNT(DISTINCT order_id) AS total_orders,
    ROUND(SUM(price), 2) AS total_revenue,
    ROUND(AVG(price), 2) AS avg_order_value
FROM order_items;
"""

df_summary = pd.read_sql_query(query_summary, conn)
df_summary

   total_orders  total_revenue  avg_order_value
0         98666     13591643.7           120.65

In [ ]:
# Query 2: Top 5 bestseller product according revenue
query_top_products = """
SELECT 
    p.product_category_name AS category,
    COUNT(i.order_id) AS total_items_sold,
    ROUND(SUM(i.price), 2) AS total_revenue
FROM order_items i
JOIN products p ON i.product_id = p.product_id
WHERE p.product_category_name IS NOT NULL
GROUP BY p.product_category_name
ORDER BY total_revenue DESC
LIMIT 5;
"""

df_top_products = pd.read_sql_query(query_top_products, conn)
df_top_products

                 category  total_items_sold  total_revenue
0            beleza_saude              9670     1258681.34
1      relogios_presentes              5991     1205005.68
2         cama_mesa_banho             11115     1036988.68
3           esporte_lazer              8641      988048.97
4  informatica_acessorios              7827      911954.32

In [12]:
#Table visualisation
df_top_products.style.bar(subset=['total_revenue'], color="#9f41ce")

In [ ]:
# Query for monthly revenue
query_trend = """
SELECT 
    substr(shipping_limit_date, 1, 7) AS month,
    COUNT(order_id) AS total_orders,
    ROUND(SUM(price), 2) AS monthly_revenue
FROM order_items
GROUP BY month
ORDER BY month ASC;
"""

df_trend = pd.read_sql_query(query_trend, conn)

# first month
df_trend.head(10)

     month  total_orders  monthly_revenue
0  2016-09             4           194.47
1  2016-10           365         49580.55
2  2016-12             1            10.90
3  2017-01           681         80124.74
4  2017-02          1866        245982.01
5  2017-03          2751        343242.60
6  2017-04          2364        308148.32
7  2017-05          4150        505655.46
8  2017-06          3801        469001.05
9  2017-07          4116        465282.10